[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 120

[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'

[tool.django-stubs]
django_settings_module = "monitora_csfd_homework.settings"