# Generated by Django 4.2.1 on 2023-05-20 15:17
# type: ignore

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # ignore

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("movies", models.ManyToManyField(related_name="actors", to="app.movie")),
            ],
        ),
    ]
