# Generated by Django 4.2.1 on 2023-05-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csfd_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('title_normalized', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='app_movie_title_3d38f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csfd_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('name_normalized', models.CharField(max_length=150)),
                ('movies', models.ManyToManyField(related_name='actors', to='app.movie')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='app_actor_name_04b25f_idx')],
            },
        ),
    ]
